### ISSUE TITLE
PIP3 not checked for, but required

### ISSUE THREAD

**Issue by psiberfunk** [sporkus/probe_accuracy_tests#1]
PIP3 is required on raspbian, but is often not installed by default on distributions like MainSail OS which is very common in the klipper world.

On attempted install , though I have python3 installed Pip3 is NOT installed.. and the installation should fail, not succeed... however it installs "half-baked" at present:

`pi@pumpkin:~ $ curl -sSL https://raw.githubusercontent.com/sporkus/probe_accuracy_tests/master/install.sh | bash
Cloning repo
Cloning into 'probe_accuracy_tests'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 63 (delta 27), reused 53 (delta 17), pack-reused 0
Unpacking objects: 100% (63/63), done.
Install python packages
bash: line 8: pip3: command not found
Installation finished`

This should not happen .. instead the install should instruct the user to install PIP3 first, or offer to do it for them via:

sudo apt-get install python3-pip

**Comment by sporkus** [comment]
@psiberfunk good point. The install script was very quickly slapped together. I didn't realize that pip3 didn't come with the typical mainsail or fluidd installation.

I will add additional checks and make sure it can handle a dangling install.
