### ISSUE TITLE
Tap with sensorless X/Y doesn't respect safe Z

### ISSUE THREAD

**Issue by ressu** [sporkus/probe_accuracy_tests#17]
When using sensorless homing for X/Y and Tap, the probe script falls back into asking about safe Z height. The first move respects the safe height, but after probing the bed the nozzle isn't lifted from the bed and instead it's dragged across to the next probe point.

This is an interaction between sensorless homing and more specifically the variable homing current that is needed for smooth and reliable homing in my setup. Because I use variable current, I need to use homing override which isn't compatible with safe homing. This leads to the first problem, which is that the script gets confused into thinking that I'm using a TAP and asks about safe homing distance.

The second problem comes from the fact that the probe sequence ends with the nozzle touching the bed. Which means that when the move to the next probe location is requested, the nozzle is dragged across the bed. To resolve the issue I made the `safe_z` variable global within `move_to_safe_z()` and added a call to `move_to_safe_z()` in the beginning of `move_to_loc()`

This makes things work nicely.

PS. if you set a license for the repo, I could send this as a PR.

**Comment by sporkus** [comment]
@ressu I am not familiar with sensorless homing, thanks for making this more versatile. I'll add a license. Please open a PR for your work
