### ISSUE TITLE
Error running install script

### ISSUE THREAD

**Issue by Kosh42** [sporkus/probe_accuracy_tests#21]
When running the scrip the git pulls fine, but then I get this:

```
Traceback (most recent call last):
  File "/home/tim/.local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named pip._internal.cli.main
```

Same when I go in to the cloned directory and run ./install.py.

**Comment by Kosh42** [comment]
Update: Running `pip3 install -r requirements.txt` generates the same error.

**Comment by sporkus** [comment]
Maybe something is wrong with your python installation.

You can try. Hope that helps!
python -m pip install --upgrade pip

**Comment by Kosh42** [comment]
Looks like I was. Was just about to close this as I force reinstalled and all seems good. TY for the awesome work on this. Have used it in the past and love it.
