### ISSUE TITLE
Probe could hit the dock or be out of range

### ISSUE THREAD

**Issue by fbeauKmi** [sporkus/probe_accuracy_tests#4]
While performing the repeatability test, the probe can hit the dock due to get_random_loc().
If xmin or ymin are negative it can produce out of range value 
```
        x = np.random.random() * (xmax - xmin - **margin**) + margin
        y = np.random.random() * (ymax - ymin - **margin**) + margin

```
gives position range : ( margin, max-min) . To keep margin and accuracy you should use

```
        x = np.random.random() * (xmax - xmin - 2 * margin) + margin + xmin
        y = np.random.random() * (ymax - ymin - 2 * margin) + margin + ymin

```
position range : ( min + margin, max - margin )

**Comment by sporkus** [comment]
@fbeauKmi Thanks for fixing my math. Implemented.
