### ISSUE TITLE
Readings are not correctly using "Skip first probe"

### ISSUE THREAD

**Issue by jktightwad** [sporkus/probe_accuracy_tests#5]
When running without the "keep_first" enabled the 1st probe is still being read, even when it's disabled in the config.  This results in readings in the Mainsail console not matching the results in the SSH console and the graphs.

```
                                   min     max    first     last       mean       std  count   range   drift
test                                                                                                        
1:corner 30samples (30, 250)   14.6975  14.730  14.6975  14.7275  14.724583  0.005689     30  0.0325  0.0300
2:corner 30samples (270, 250)  14.6475  14.715  14.6475  14.7150  14.712167  0.012330     30  0.0675  0.0675
3:corner 30samples (30, 10)    14.7125  14.725  14.7125  14.7250  14.723167  0.002537     30  0.0125  0.0125
4:corner 30samples (270, 10)   14.6975  14.720  14.6975  14.7175  14.716500  0.003917     30  0.0225  0.0200
```

```
probe accuracy results: maximum 14.730000, minimum 14.697500, range 0.032500, average 14.724583, median 14.725000, standard deviation 0.005593
probe accuracy results: maximum 14.715000, minimum 14.647500, range 0.067500, average 14.712167, median 14.715000, standard deviation 0.012123
probe accuracy results: maximum 14.725000, minimum 14.712500, range 0.012500, average 14.723167, median 14.722500, standard deviation 0.002494
probe accuracy results: maximum 14.720000, minimum 14.697500, range 0.022500, average 14.716500, median 14.717500, standard deviation 0.003851
```

**Comment by sporkus** [comment]
![image](https://user-images.githubusercontent.com/102923689/182033729-bcd9023d-6baa-402a-973b-8223fd8899ad.png)
I don't see how the 1st probe sample is still included in the calculation.  Min, first from console matches mainsail output.

If you're talking about standard deviation calculation, that might be sample vs population standard deviation.

To confirm you can run a test with smaller samples, e.g. 5 probes. If your machine is dropping first probe, it will probe 6 times. The webUI will show 6 z heights and the probe_accuracy output will use the last 5. This script will also use the last five for calculation by default (keep_first=False). If you look at the graphs you should see only 5 points also.

**Comment by sporkus** [comment]
Feel free to re-open if you have any updates @jktightwad
